### ISSUE TITLE
meraki_networks_appliance_traffic_shaping_rules input variable issue

### ISSUE THREAD

**Issue by Fran-E** [cisco-open/terraform-provider-meraki#134]
**Prerequisites**
* [yes] Have you tested the operation in the API directly?
* [yes] Do you have the latest Terraform provider version?
* [yes] Review the [compatibility matrix](https://github.com/meraki/terraform-provider-meraki/tree/main#compatibility-matrix) before opening an issue. 

**Describe the bug**
Problem on this ressource meraki_networks_appliance_traffic_shaping_rules, in the rules.definitions, "value" variable have a problem if 
 "type" = "application", this variable become "value_obj" to make it working.

**Expected behavior**
Or an update on the documentation is required to explain about "value_obj"
Or there is something to solve in the code, I expect this is something here because the usage of this ressource make the "plan" or the "apply" too much long. I tested the GET on the API directly and respond was less than 2sec. Here the "plan" is about 1-2 minutes par networks.

**Environment (please complete the following information):**
* Meraki Dashboard version: n568.meraki.com
* Terraform version: 1.9.3
* Meraki provider version: 0.2.10-alpha
* OS Version: Windows 11

**Comment by fmunozmiranda** [comment]
Documentation has been updated, the resource takes longer in Terraform because extra validations are done to handle this resource, since it has exceptions in which an attribute can vary in type. Thank you for your feedback. It would be updated in next release, closing this issue, if you have something else about this, please reopen it.
